exam-application:
  filename: questions.csv
  required-correct-answers: 3
  question-attempts: 2
  shuffle-answers: true
  locales:
    - ru
    - en
spring:
  messages:
    # Если местонахождение не нашли, используем бандл по умолчанию, а не бандл с системным местонахождением
    fallback-to-system-locale: false
