--liquibase formatted sql

--changeset VolginT:createTables
CREATE TABLE genres  (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_genres PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE authors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_authors PRIMARY KEY,
    fio      VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE books (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_books PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    published DATE NOT NULL,
    genre_id BIGINT,
    author_id BIGINT,
    FOREIGN KEY (genre_id) REFERENCES genres(id),
    FOREIGN KEY (author_id) REFERENCES authors(id)
);

CREATE TABLE comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_comments PRIMARY KEY,
    text    TEXT NOT NULL,
    book_id BIGINT,
    FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_users PRIMARY KEY,
    user_name VARCHAR (255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255)
);
